---
sysctl_params:
    net.ipv4.ip_forward: "1"
    echo net.ipv4.conf.all.forwarding: "1"

routes_params:
   centralRouter:
    eth2:
      routes_file: route-eth2
      network: 192.168.2.0/24
      via: 192.168.100.2
      net_interface: eth2
    eth3:
      routes_file: route-eth3
      network: 192.168.1.0/24
      via: 192.168.200.2
      net_interface: eth3


gateway:
  ip: 192.168.255.1
  interface: eth1